before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: MjlOEMq4S9IH0wzUNrLYOiiRn5utkdEQnwUMMNuTCj7aZJfpuYw80g3ysBuN5MXFYqpqtKVoTzNYITvrI3CNzg4bVtmohiSw2h9xPrjPzq+kR2MkHGmWRNjWR9kgBnum8pd+bjMY1CHGSE0MkfUrZJ37Yof/N5nVzm2fFoRc3CS4DfKrb+o2aqtIOKyopFVF3btqWPlCt6IUDMCeZCOznfUBV3a7f5qSR7W+3pSUjX/BkH51mgOoHgurQ4iVT2h0qb1x0RSvD0Es0E98wZTDLLb5BFD85o88HfKiikW2CeGw29/pGndH/m2/5G3AwhCLgnloTtDRoKqpzFEKDBgHYn6ZK6i0Ttt9d2nXzUc5RGjHqXVa4lx9hbQLR3OjcsF/c16d+RBa/GP0YLw0gd5/tEAXo+0BeHql3dgYjYaEsI4bMvVC3cKFLb/WH323sxSOMtQOtZHWGg6073Qc+JKyoqF4RK2R+06q5wmkvAXuWl+rtp38424+6vWXu8q1JjBWz2MIMtgG+mMUQvA9utj6J77BaLn9bg+DiXt1GWPCwqOdV3NRQsZfDL1qptQEuyQjTrawSevF9IljCTGhxNME3R5VcrCHmgVoI1P8tMv5HhCJCqv3bV0Bmal2k70YUXhOlsFqEqtPm2mSupeooBczbKKCl9LLO3/ndA/kaME7hvs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
